# Generated by Django 4.0.4 on 2022-07-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('is_read', models.BooleanField()),
            ],
        ),
    ]
